services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./assets:/var/www/html/assets
      - user_data:/var/www/html/data
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: .
    volumes:
      - ./public:/var/www/html
      - ./assets:/var/www/html/assets
      - ./db/migrations:/var/www/html/migrations
      - user_data:/var/www/html/data
      - db_data:/var/www/html/db
    command: sh -c "sh /usr/bin/db-setup.sh && chown -R www-data:www-data /var/www/html/data /var/www/html/db && exec php-fpm"

volumes:
  user_data:
  db_data:

networks:
  default:
    driver: bridge
